[package]
name = "fenix-polkit-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fenix-polkit-agent"
path = "src/main.rs"

[dependencies]
zbus = { version = "4", default-features = false, features = ["tokio"] }
gtk4 = "0.9"
async-channel = "2"
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
